spring:
  application:
    name: mall-admin
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization
  secret: mall-admin-secret
  expiration: 315360000
  tokenHead: "Bearer "

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400

secure:
  ignored:
    urls:
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v3/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: test
    accessKeySecret: test
    bucketName: macro-oss
    policy:
      expire: 300
    maxSize: 10
    callback: http://39.98.190.128:8080/aliyun/oss/callback
    dir:
      prefix: mall/images/